### PR TITLE
Fix for #340

### PR DESCRIPTION
**Pull request by nasko**
I've modified only those tests, that are concerned with the changed implementation.
However, although I tried to make the tests both ZF2 and ZF3-compatible, I'm not sure if the implementation will also work with ZF2, or if it would be BC

### CODE REVIEW

**Comment by prolic** [comment]
@nasko I needed to revert, 4 tests are failing with zf3:

```
There were 4 errors:

1) ZfcRbacTest\Guard\ControllerGuardTest::testProperlySetUnauthorizedAndTriggerEventOnUnauthorization

Error: Call to undefined method Mock_EventManagerInterface_9d9e4254::triggerEvent()

/home/travis/build/ZF-Commons/zfc-rbac/src/ZfcRbac/Guard/AbstractGuard.php:74

/home/travis/build/ZF-Commons/zfc-rbac/tests/ZfcRbacTest/Guard/ControllerGuardTest.php:522

2) ZfcRbacTest\Guard\ControllerPermissionsGuardTest::testProperlySetUnauthorizedAndTriggerEventOnUnauthorization

Error: Call to undefined method Mock_EventManagerInterface_9d9e4254::triggerEvent()

/home/travis/build/ZF-Commons/zfc-rbac/src/ZfcRbac/Guard/AbstractGuard.php:74

/home/travis/build/ZF-Commons/zfc-rbac/tests/ZfcRbacTest/Guard/ControllerPermissionsGuardTest.php:511

3) ZfcRbacTest\Guard\RouteGuardTest::testProperlySetUnauthorizedAndTriggerEventOnUnauthorization

Error: Call to undefined method Mock_EventManagerInterface_9d9e4254::triggerEvent()

/home/travis/build/ZF-Commons/zfc-rbac/src/ZfcRbac/Guard/AbstractGuard.php:74

/home/travis/build/ZF-Commons/zfc-rbac/tests/ZfcRbacTest/Guard/RouteGuardTest.php:463

4) ZfcRbacTest\Guard\RoutePermissionsGuardTest::testProperlySetUnauthorizedAndTriggerEventOnUnauthorization

Error: Call to undefined method Mock_EventManagerInterface_9d9e4254::triggerEvent()

/home/travis/build/ZF-Commons/zfc-rbac/src/ZfcRbac/Guard/AbstractGuard.php:74

/home/travis/build/ZF-Commons/zfc-rbac/tests/ZfcRbacTest/Guard/RoutePermissionsGuardTest.php:441
```

**Comment by nasko** [comment]
This beats me - how is it possible the tests fail with zf3?! `EventManagerInterface::triggerEvent(EventInterface $event)` has been added in [September 2015 with this commit](https://github.com/zendframework/zend-eventmanager/commit/c1c825556b53fd866d84907e7b50645eea2f76a0)

**Comment by prolic** [comment]
Thanks for the PR, though, I'll try to fix it later.

**Comment by prolic** [comment]
Sorry, my fault, tests are failing with ZF2, not with ZF3. Problem is, there is no triggerEvent method in ZF2.

**Comment by prolic** [comment]
fixed now.

**Comment by nasko** [comment]
Thanks @prolic!

**Pull request merged**
